ORF:
  HILL_CLIMBING_MAX_ITERATIONS: 50
  # Optional values:
  #   * single_codon_global_ratio
  #   * single_codon_local_ratio
  #   * single_codon_global_diff
  #   * single_codon_local_diff
  #   * hill_climbing_average
  #   * hill_climbing_weakest_link
  INITIATION_CODONS: 12
  MAX_N_OPTIMIZED_SEQS: 10
