ORF:
  HILL_CLIMBING_MAX_ITERATIONS: 50
  # Optional values:
  #   * single_codon_global
  #   * single_codon_local
  #   * hill_climbing_average
  #   * hill_climbing_weakest_link
  TRANSLATION_FUNCTION: hill_climbing_average
  MAX_N_OPTIMIZED_SEQS: 10
