MODEL_PREFERENCES:
  RESTRICTION_ENZYMES: False
  TRANSLATION: True
  TRANSCRIPTION: False
  # Optional values:
  #   * single_codon_global
  #   * single_codon_local
  #   * zscore_hill_climbing_average
  #   * zscore_hill_climbing_weakest_link
  TRANSLATION_FUNCTION: zscore_hill_climbing_average

ORF:
  HILL_CLIMBING_MAX_ITERATIONS: 50